# config/packages/security.yaml
security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$jxGxcIuqDju'
                        roles: ['ROLE_ADMIN']

    firewalls:
        secured_area:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
